# From: rc/dein.vim

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = 'runtime add/denite.vim'
#hook_source = 'runtime source/denite.vim'
hook_post_source = 'runtime post/denite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_func = ['unite#']
on_cmd = ['Unite']

[[plugins]]
repo = 'neoclide/coc-denite'
on_source = 'denite.nvim'

#[[plugins]]
#repo = 'lighttiger2505/denite-vim-lsp'
## denite source for vim-lsp.
#on_source = 'denite.nvim'
#hook_post_source = 'runtime add/denite-lsp.vim'

#[ Matcher ]
#[[plugins]]
#repo = 'nekowasabi/denite-migemo'
#on_source = 'denite.nvim'
#hook_post_source = 'runtime add/denite-migemo.vim'

#[[plugins]]
#repo = 'nixprime/cpsm'
## A matcher developped for 'CtrlP'
#build = '''
#type cpsm || pip install --user cpsm
#'''
#on_source = 'denite.nvim'
#hook_post_update = 'bash install.sh'

#[[plugins]]
#repo = 'raghur/fruzzy'
#on_source = 'denite.nvim'
#hook_done_update = 'call fruzzy#install()'
#hook_post_source = 'runtime add/fruzzy.vim'

#[[plugins]]
#repo = 'dunstontc/projectile.nvim'
#on_source = 'denite.nvim'
#hook_post_source = 'runtime add/projectile.vim'

#[ Extensions ]
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'

[[plugins]]
repo = 'delphinus/vim-denite-scriptnames'
on_source = 'denite.nvim'

[[plugins]]
repo = 'ozelentok/denite-gtags'
on_source = 'denite.nvim'

[[plugins]]
repo = 'rafi/vim-denite-session'
on_source = 'denite.nvim'

[[plugins]]
repo = 'neoclide/denite-git'
on_source = 'denite.nvim'

[[plugins]]
repo = 'deresmos/denite-gitdiff'
on_source = 'denite.nvim'

#[[plugins]]
#repo = 'Shougo/neoyank.vim'
#on_source = 'denite.nvim'

#[[plugins]]
#repo = 'zacharied/denite-nerdfont'
#on_source = 'denite.nvim'
#hook_post_source = 'runtime add/denite-nerdfont.vim'
[[plugins]]
repo = 'Shougo/neossh.vim'
on_source = ['unite.vim', 'denite.nvim']
