# From: dein/dein.vim

# Note: Don't locate the plugins under $MYVIMRC for dein's hook.
[[plugins]]
repo = 'kaile256/vim-among_HML'
on_func = ['among_HML#', 'among_HML#fork#']
hook_add = 'runtime add/among_HML.vim'

[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-spell-temporary'
on_map = {nix = '<Plug>(spellTMP-suggestion'}
hook_add = 'runtime add/spell-temporary.vim'

#[ Fold ]
[[plugins]]
repo = 'kaile256/vim-foldpeek'
if = "&bt !=# 'terminal'"
on_event = ['BufWinEnter']
hook_source = 'runtime source/foldpeek.vim'
#hook_post_source = 'runtime post/foldpeek.vim'

[[plugins]]
repo = 'kaile256/vim-SandJoin'
on_map = {nx = '<Plug>(SandJoin-'}
on_cmd = ['SandJoin']
on_func = ['SandJoin#']
hook_add = 'runtime add/SandJoin.vim'
hook_source = 'runtime source/SandJoin.vim'

#[[plugins]]
#repo = 'kaile256/vim-sensible_K'
## Note: the plugin defines no map/cmd, only using augroup.
#on_event = 'VimEnter'
#hook_add = 'runtime add/sensible_K.vim'
#
#[[plugins]]
#repo = 'kaile256/vim-window-picker'
#on_cmd = ['WindowPKreduce', 'WindowPKpick', 'WindowPKoly', 'WindowPKfloating', 'WindowPKcopy', 'WindowPKtabGive']
#hook_add = 'runtime add/window-picker.vim'

#[[plugins]]
#repo = 'kaile256/vim-keymaps-dealer'
## Note: must load the plugin before mapped, cannot lazy-load.
#on_event = 'VimEnter'
#hook_source = 'runtime source/keymaps-dealer.vim'
## Note: autoload-functions in vimrc must be called after loading the autoload/.
#hook_post_source = 'runtime post/keymaps-dealer.vim'
#
#[[plugins]]
#repo = 'kaile256/vim-lines-in-functions'
#on_cmd = ['LinesFunctions']

#[[plugins]]
#repo = 'kaile256/vim-fvf'
#on_event = 'VimEnter'
#rev = 'refactoring'
##rev = 'verbose_commands'
#hook_add = 'runtime add/fzf.vim'
#hook_source = 'runtime source/fzf.vim'
#hook_post_source = 'runtime post/fzf.vim'

#[[plugins]]
#repo = 'kaile256/vim-findpath'
#on_cmd = 'FindPath'
##hook_add = 'runtime add/findpath.vim'
#
#[ Help ]
[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-help-toc'
on_ft = ['help', 'man']
hook_source = 'runtime source/help-toc.vim'

#[ Git ]
[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-fzf-git'
type = 'git'
on_event = ['BufRead']
on_cmd = ['GStashes']
on_func = [
'fzf#git#',
'fzf#git#stash#',
]
#hook_add = 'runtime add/fzf-git.vim'

[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-yaml-fold'
on_func =  ['yamlfold#activate']
on_ft = [
  'sh',
  'zsh',
  'bash',
  'eyaml'
  'python',
  'raml',
  'sls',
  'yaml',
]
hook_source = 'runtime source/yaml-fold.vim'

#[[plugins]]
#repo = 'kaile256/vim-viml-fold'
#on_ft = ['vim']

#[[plugins]]
#repo = 'kaile256/vim-markdown-fold'
#on_ft = ['markdown']

[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-toml-fold'
# a fork from matze/vim-ini-fold
on_ft = [
  'cfg'
  'conf',
  'config',
  'desktop',
  'dosini',
  'gitconfig',
  'markdown',
  'toml',
]
hook_source = 'runtime source/toml-fold.vim'

[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-option-check'
on_cmd = ['VimOptCheck']
hook_add = 'runtime add/option-check.vim'

#[ Memo ]
[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-private-note'
on_cmd = ['Note']
hook_add = 'runtime add/private-note.vim'
hook_source = 'runtime source/private-note.vim'

#[ Snippet ]
[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-snip-functions'
on_source = ['neosnippet.vim', 'ultisnips']
on_func = ['snip#vim#']

[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-clever-newline'
on_event = ['BufAdd']

#[[plugins]]
#repo = '$DEIN_PRIVATE_HOME/vim-font-resize'

#[ SQL ]
[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-sql-uppercase'
on_ft = ['sql', 'mysql']
# Note: kinda fork of alcesleo/vim-uppercase-sql

#[ Colorscheme ]
[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-highlight-info'
on_cmd = ['HlInfo']

#[ Indent ]
[[plugins]]
repo = '$DEIN_PRIVATE_HOME/vim-virtual-indent'
# Ref: https://www.reddit.com/r/neovim/comments/fxjjqh/indent_guides_on_blank_lines_with_virtual_text/?utm_name=iossmf
if = 'has("nvim")'
on_event = ['BufRead']
